# Introducción a Python, PyTorch y Tensores

**Aprendizaje Profundo - UNSAM**

En este notebook cubriremos:
1. Repaso rápido de Python y NumPy
2. Introducción a PyTorch
3. Tensores: operaciones básicas y manipulación
4. Autograd: diferenciación automática

## 1. Repaso de Python y NumPy

### Listas y Arrays

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Listas en Python
lista = [1, 2, 3, 4, 5]
print(f"Lista: {lista}")
print(f"Tipo: {type(lista)}")

# Arrays de NumPy
array = np.array([1, 2, 3, 4, 5])
print(f"\nArray: {array}")
print(f"Tipo: {type(array)}")
print(f"Forma: {array.shape}")
print(f"Dtype: {array.dtype}")

Lista: [1, 2, 3, 4, 5]
Tipo: <class 'list'>

Array: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Forma: (5,)
Dtype: int64


### Operaciones con NumPy

In [2]:
# Creación de arrays
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
random = np.random.randn(3, 3)

print("Zeros (3x4):")
print(zeros)
print("\nOnes (2x3):")
print(ones)
print("\nRandom (3x3):")
print(random)

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Random (3x3):
[[ 1.33039201 -1.14287932 -1.58294831]
 [ 0.59839307 -1.28623486 -1.83886645]
 [ 0.53144202  1.18050714  0.21892002]]


In [3]:
# Operaciones vectorizadas
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a · b (producto punto) = {np.dot(a, b)}")

# Operaciones con matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("\nMultiplicación de matrices:")
print(A @ B)  # Equivalente a np.matmul(A, B)

a + b = [5 7 9]
a * b = [ 4 10 18]
a · b (producto punto) = 32

Multiplicación de matrices:
[[19 22]
 [43 50]]


## 2. Introducción a PyTorch

PyTorch es una biblioteca de deep learning desarrollada por Facebook. Es popular por su facilidad de uso y su naturaleza "pythonic".

In [4]:
import torch

print(f"Versión de PyTorch: {torch.__version__}")
print(f"CUDA disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Dispositivo CUDA: {torch.cuda.get_device_name(0)}")

Versión de PyTorch: 1.13.1+cu117
CUDA disponible: True
Dispositivo CUDA: NVIDIA RTX A5000


## 3. Tensores en PyTorch

Los tensores son la estructura de datos fundamental en PyTorch. Son similares a los arrays de NumPy, pero pueden ejecutarse en GPU y tienen capacidad de diferenciación automática.

### Creación de Tensores

In [5]:
# Diferentes formas de crear tensores

# Desde una lista
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print(f"Desde lista: {tensor_from_list}")

# Desde un array de NumPy
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(f"Desde NumPy: {tensor_from_numpy}")

# Tensores de ceros y unos
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 3)
print(f"\nZeros (3x4):\n{zeros}")
print(f"\nOnes (2x3):\n{ones}")

# Tensores aleatorios
random_uniform = torch.rand(3, 3)  # Uniforme [0, 1)
random_normal = torch.randn(3, 3)  # Normal(0, 1)
print(f"\nAleatorio uniforme (3x3):\n{random_uniform}")
print(f"\nAleatorio normal (3x3):\n{random_normal}")

# Tensor con valores específicos
filled = torch.full((2, 3), 7.5)
print(f"\nLlenado con 7.5:\n{filled}")

Desde lista: tensor([1, 2, 3, 4, 5])
Desde NumPy: tensor([1, 2, 3])

Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Aleatorio uniforme (3x3):
tensor([[0.6674, 0.8186, 0.3081],
        [0.5194, 0.2076, 0.4581],
        [0.7194, 0.6299, 0.2623]])

Aleatorio normal (3x3):
tensor([[-1.5803,  0.6048,  0.4413],
        [ 0.1277,  2.0429,  2.2948],
        [-0.2830, -0.7918, -0.9609]])

Llenado con 7.5:
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])


### Propiedades de los Tensores

In [6]:
tensor = torch.randn(3, 4, 5)

print(f"Tensor: {tensor.shape}")
print(f"Forma (shape): {tensor.shape}")
print(f"Tamaño (size): {tensor.size()}")
print(f"Número de dimensiones: {tensor.ndim}")
print(f"Número total de elementos: {tensor.numel()}")
print(f"Tipo de dato: {tensor.dtype}")
print(f"Dispositivo: {tensor.device}")

Tensor: torch.Size([3, 4, 5])
Forma (shape): torch.Size([3, 4, 5])
Tamaño (size): torch.Size([3, 4, 5])
Número de dimensiones: 3
Número total de elementos: 60
Tipo de dato: torch.float32
Dispositivo: cpu


### Tipos de Datos

In [7]:
# Diferentes tipos de datos
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
long_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

print(f"Float32: {float_tensor.dtype}")
print(f"Int32: {int_tensor.dtype}")
print(f"Long: {long_tensor.dtype}")
print(f"Float64: {double_tensor.dtype}")

# Conversión de tipos
converted = float_tensor.long()
print(f"\nConvertido a long: {converted} - {converted.dtype}")

Float32: torch.float32
Int32: torch.int32
Long: torch.int64
Float64: torch.float64

Convertido a long: tensor([1, 2, 3]) - torch.int64


### Operaciones con Tensores

In [8]:
# Operaciones aritméticas básicas
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"a = {a}")
print(f"b = {b}")
print(f"\na + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

# Operaciones in-place (modifican el tensor)
c = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"\nAntes: c = {c}")
c.add_(5)  # Operaciones in-place terminan en _
print(f"Después de c.add_(5): c = {c}")

a = tensor([1., 2., 3.])
b = tensor([4., 5., 6.])

a + b = tensor([5., 7., 9.])
a - b = tensor([-3., -3., -3.])
a * b = tensor([ 4., 10., 18.])
a / b = tensor([0.2500, 0.4000, 0.5000])
a ** 2 = tensor([1., 4., 9.])

Antes: c = tensor([1., 2., 3.])
Después de c.add_(5): c = tensor([6., 7., 8.])


In [9]:
# Producto punto y multiplicación de matrices
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

# Producto punto
dot_product = torch.dot(a, b)
print(f"Producto punto: {dot_product}")

# Multiplicación de matrices
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"\nMatriz A:\n{A}")
print(f"\nMatriz B:\n{B}")
print(f"\nA @ B:\n{A @ B}")
print(f"\ntorch.matmul(A, B):\n{torch.matmul(A, B)}")
print(f"\nA.mm(B):\n{A.mm(B)}")

Producto punto: 32.0

Matriz A:
tensor([[1., 2.],
        [3., 4.]])

Matriz B:
tensor([[5., 6.],
        [7., 8.]])

A @ B:
tensor([[19., 22.],
        [43., 50.]])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])

A.mm(B):
tensor([[19., 22.],
        [43., 50.]])


### Indexación y Slicing

In [10]:
tensor = torch.arange(20).reshape(4, 5)
print(f"Tensor original:\n{tensor}")

# Indexación
print(f"\nElemento [2, 3]: {tensor[2, 3]}")
print(f"Primera fila: {tensor[0, :]}")
print(f"Segunda columna: {tensor[:, 1]}")

# Slicing
print(f"\nPrimeras 2 filas:\n{tensor[:2, :]}")
print(f"\nÚltimas 3 columnas:\n{tensor[:, -3:]}")
print(f"\nSubmatriz [1:3, 2:4]:\n{tensor[1:3, 2:4]}")

Tensor original:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

Elemento [2, 3]: 13
Primera fila: tensor([0, 1, 2, 3, 4])
Segunda columna: tensor([ 1,  6, 11, 16])

Primeras 2 filas:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Últimas 3 columnas:
tensor([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])

Submatriz [1:3, 2:4]:
tensor([[ 7,  8],
        [12, 13]])


### Reshape y View

In [11]:
tensor = torch.arange(12)
print(f"Original: {tensor}")
print(f"Shape: {tensor.shape}")

# Reshape
reshaped = tensor.reshape(3, 4)
print(f"\nReshaped (3x4):\n{reshaped}")

# View (similar a reshape pero requiere memoria contigua)
viewed = tensor.view(4, 3)
print(f"\nView (4x3):\n{viewed}")

# Inferir una dimensión con -1
auto_shape = tensor.view(2, -1)
print(f"\nView (2, -1) = {auto_shape.shape}:\n{auto_shape}")

# Flatten (aplanar)
flattened = reshaped.flatten()
print(f"\nFlattened: {flattened}")

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

View (4x3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

View (2, -1) = torch.Size([2, 6]):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


### Operaciones de Reducción

In [12]:
tensor = torch.randn(3, 4)
print(f"Tensor:\n{tensor}")

# Operaciones sobre todo el tensor
print(f"\nSuma total: {tensor.sum()}")
print(f"Media: {tensor.mean()}")
print(f"Máximo: {tensor.max()}")
print(f"Mínimo: {tensor.min()}")
print(f"Desviación estándar: {tensor.std()}")

# Operaciones por dimensión
print(f"\nSuma por filas (dim=1): {tensor.sum(dim=1)}")
print(f"Media por columnas (dim=0): {tensor.mean(dim=0)}")

# Argmax y Argmin
print(f"\nÍndice del máximo: {tensor.argmax()}")
print(f"Índice del máximo por fila: {tensor.argmax(dim=1)}")

Tensor:
tensor([[ 0.0439,  0.7813, -0.6581, -2.0154],
        [ 0.2960, -1.1674, -1.0371, -0.4934],
        [ 1.0247, -0.8001,  2.0435,  0.0061]])

Suma total: -1.9757624864578247
Media: -0.16464687883853912
Máximo: 2.043485164642334
Mínimo: -2.015435218811035
Desviación estándar: 1.1044349670410156

Suma por filas (dim=1): tensor([-1.8483, -2.4017,  2.2742])
Media por columnas (dim=0): tensor([ 0.4549, -0.3954,  0.1161, -0.8342])

Índice del máximo: 10
Índice del máximo por fila: tensor([1, 0, 2])


### Concatenación y Stacking

In [13]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor a:\n{a}")
print(f"\nTensor b:\n{b}")

# Concatenar
cat_dim0 = torch.cat([a, b], dim=0)
cat_dim1 = torch.cat([a, b], dim=1)
print(f"\nConcatenado (dim=0):\n{cat_dim0}")
print(f"\nConcatenado (dim=1):\n{cat_dim1}")

# Stack (crea una nueva dimensión)
stacked = torch.stack([a, b])
print(f"\nStacked: shape {stacked.shape}\n{stacked}")

Tensor a:
tensor([[1, 2],
        [3, 4]])

Tensor b:
tensor([[5, 6],
        [7, 8]])

Concatenado (dim=0):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenado (dim=1):
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

Stacked: shape torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## 4. Autograd: Diferenciación Automática

Una de las características más importantes de PyTorch es su capacidad para calcular gradientes automáticamente.

### Gradientes Básicos

In [14]:
# Crear un tensor con requires_grad=True
x = torch.tensor(2.0, requires_grad=True)
print(f"x = {x}")
print(f"requires_grad: {x.requires_grad}")

# Definir una función: y = x^2 + 3
y = x**2 + 3
print(f"\ny = x^2 + 3 = {y}")

# Calcular gradientes
y.backward()  # dy/dx

# El gradiente se almacena en x.grad
print(f"\ndy/dx = 2x = {x.grad}")
print(f"En x=2: dy/dx = {x.grad.item()}")

x = 2.0
requires_grad: True

y = x^2 + 3 = 7.0

dy/dx = 2x = 4.0
En x=2: dy/dx = 4.0


In [15]:
# Ejemplo más complejo
x = torch.tensor(3.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)

# z = x^2 * y + y^3
z = x**2 * y + y**3
print(f"x = {x.item()}, y = {y.item()}")
print(f"z = x^2 * y + y^3 = {z.item()}")

# Calcular gradientes
z.backward()

print(f"\n∂z/∂x = 2xy = {x.grad.item()}")
print(f"∂z/∂y = x^2 + 3y^2 = {y.grad.item()}")

# Verificar manualmente
print(f"\nVerificación:")
print(f"2 * {x.item()} * {y.item()} = {2 * x.item() * y.item()}")
print(f"{x.item()}^2 + 3 * {y.item()}^2 = {x.item()**2 + 3 * y.item()**2}")

x = 3.0, y = 2.0
z = x^2 * y + y^3 = 26.0

∂z/∂x = 2xy = 12.0
∂z/∂y = x^2 + 3y^2 = 21.0

Verificación:
2 * 3.0 * 2.0 = 12.0
3.0^2 + 3 * 2.0^2 = 21.0


### Gradientes con Vectores

In [16]:
# Vector de entrada
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"x = {x}")

# Función: y = 2 * x^2
y = 2 * x**2
print(f"y = 2 * x^2 = {y}")

# Para vectores, necesitamos especificar un vector gradiente
y.backward(torch.ones_like(y))

print(f"\ndy/dx = 4x = {x.grad}")

x = tensor([1., 2., 3.], requires_grad=True)
y = 2 * x^2 = tensor([ 2.,  8., 18.], grad_fn=<MulBackward0>)

dy/dx = 4x = tensor([ 4.,  8., 12.])


### Control de Gradientes

In [17]:
# Desactivar el seguimiento de gradientes
x = torch.tensor(2.0, requires_grad=True)

# Con torch.no_grad()
with torch.no_grad():
    y = x**2
    print(f"Dentro de no_grad: y.requires_grad = {y.requires_grad}")

# Fuera del contexto
z = x**2
print(f"Fuera de no_grad: z.requires_grad = {z.requires_grad}")

# Detach (crea un nuevo tensor sin gradientes)
w = x**2
w_detached = w.detach()
print(f"\nw.requires_grad = {w.requires_grad}")
print(f"w_detached.requires_grad = {w_detached.requires_grad}")

Dentro de no_grad: y.requires_grad = False
Fuera de no_grad: z.requires_grad = True

w.requires_grad = True
w_detached.requires_grad = False


### Limpiar Gradientes

In [18]:
x = torch.tensor(2.0, requires_grad=True)

# Primera operación
y = x**2
y.backward()
print(f"Primer gradiente: {x.grad}")

# Segunda operación sin limpiar gradientes
y = x**3
y.backward()
print(f"Segundo gradiente (acumulado): {x.grad}")

# Limpiar gradientes
x.grad.zero_()
print(f"Después de zero_(): {x.grad}")

# Tercera operación
y = x**3
y.backward()
print(f"Tercer gradiente (limpio): {x.grad}")

Primer gradiente: 4.0
Segundo gradiente (acumulado): 16.0
Después de zero_(): 0.0
Tercer gradiente (limpio): 12.0


## 5. GPU vs CPU

In [19]:
# Verificar disponibilidad de GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Dispositivo: {device}")

# Crear tensor en CPU
x_cpu = torch.randn(3, 3)
print(f"\nTensor en CPU: {x_cpu.device}")

# Mover a GPU (si está disponible)
if torch.cuda.is_available():
    x_gpu = x_cpu.to('cuda')
    print(f"Tensor en GPU: {x_gpu.device}")
    
    # Operaciones en GPU
    y_gpu = x_gpu * 2
    print(f"Resultado en GPU: {y_gpu.device}")
    
    # Mover de vuelta a CPU
    y_cpu = y_gpu.cpu()
    print(f"Resultado en CPU: {y_cpu.device}")
else:
    print("GPU no disponible. Usando CPU.")

# Forma general de mover tensores
x = torch.randn(3, 3)
x = x.to(device)
print(f"\nTensor en {x.device}")

Dispositivo: cuda

Tensor en CPU: cpu
Tensor en GPU: cuda:0
Resultado en GPU: cuda:0
Resultado en CPU: cpu

Tensor en cuda:0


## 6. Conversión entre NumPy y PyTorch

In [20]:
# NumPy a PyTorch
numpy_array = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(numpy_array)
print(f"NumPy array:\n{numpy_array}")
print(f"\nTensor de PyTorch:\n{tensor}")

# PyTorch a NumPy
tensor = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
numpy_array = tensor.numpy()
print(f"\nTensor de PyTorch:\n{tensor}")
print(f"\nNumPy array:\n{numpy_array}")

# NOTA: Comparten memoria
tensor = torch.ones(3)
numpy_array = tensor.numpy()
print(f"\nTensor original: {tensor}")
print(f"NumPy array: {numpy_array}")

tensor[0] = 99
print(f"\nDespués de modificar tensor:")
print(f"Tensor: {tensor}")
print(f"NumPy array: {numpy_array}")

NumPy array:
[[1 2]
 [3 4]]

Tensor de PyTorch:
tensor([[1, 2],
        [3, 4]])

Tensor de PyTorch:
tensor([[5., 6.],
        [7., 8.]])

NumPy array:
[[5. 6.]
 [7. 8.]]

Tensor original: tensor([1., 1., 1.])
NumPy array: [1. 1. 1.]

Después de modificar tensor:
Tensor: tensor([99.,  1.,  1.])
NumPy array: [99.  1.  1.]


## Ejercicios

1. Crea un tensor 5x5 con valores aleatorios entre 0 y 1. Calcula la suma de cada fila y cada columna.
2. Crea dos tensores 3x3 y calcula su producto matricial.
3. Crea un tensor x con requires_grad=True y calcula el gradiente de y = 3x^4 - 2x^2 + 5 en x=2.
4. Crea un tensor 4x4 y extrae la submatriz 2x2 del centro.
5. Implementa la función sigmoide σ(x) = 1/(1+e^(-x)) usando tensores de PyTorch.

In [21]:
# Ejercicio 1

In [22]:
# Ejercicio 2

In [23]:
# Ejercicio 3

In [24]:
# Ejercicio 4

In [25]:
# Ejercicio 5

## Resumen

En este notebook aprendimos:
- Los fundamentos de PyTorch y tensores
- Creación y manipulación de tensores
- Operaciones matemáticas con tensores
- Diferenciación automática con autograd
- Uso de GPU para acelerar cálculos
- Interoperabilidad entre NumPy y PyTorch

En el próximo notebook, usaremos estos conceptos para construir y entrenar redes neuronales.